const CHANGE_DRAWER_MENU = 'CHANGE_DRAWER_MENU';
const CONTENT_ABOUT = 'CONTENT_ABOUT';
const CONTENT_SKILL = 'CONTENT_SKILL';
const CONTENT_CAREER = 'CONTENT_CAREER';

export {
  CHANGE_DRAWER_MENU,
  CONTENT_ABOUT,
  CONTENT_SKILL,
  CONTENT_CAREER,
};
