const CHANGE_DRAWER_MENU = 'CHANGE_DRAWER_MENU';
const WINDOW_HEIGHT = 'WINDOW_HEIGHT';
const POST_REQUSET = 'POST_REQUSET';
const POST_SUCCESS = 'POST_SUCCESS';
const POST_FAILURE = 'POST_FAILURE';
const SHOW_MODAL = 'SHOW_MODAL';
const CHANGE_MODAL_IMAGE = 'CHANGE_MODAL_IMAGE';

export {
  CHANGE_DRAWER_MENU,
  WINDOW_HEIGHT,
  POST_REQUSET,
  POST_SUCCESS,
  POST_FAILURE,
  SHOW_MODAL,
  CHANGE_MODAL_IMAGE,
};
